articulated: false
agent_object: assets/locobot_merged
agent_radius: 0.18
agent_height: 0.88
sensor_front_bias: 0.0
hfov: 79
sensors:
- rgb_1st
action_space:
- no_op
- move_forward
- turn_left
- turn_right
- look_up
- look_down
step_size: 0.25
turn_angle: 30
tilt_angle: 30
