articulated: false
agent_object: assets/locobot_merged
agent_radius: 0.1
agent_height: 1.5
sensor_front_bias: 0.0
hfov: 90
sensors:
- rgb_1st
action_space:
- no_op
- move_forward
- turn_left
- turn_right
step_size: 0.25
turn_angle: 15
tilt_angle: 15
